server:
  port: 8088
spring:
  config:
    import: optional:configserver:http://localhost:8087
  cloud:
    config:
      profile: prod
      
      
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - refresh
        