server:
  port: 8900

spring:
  cloud:
    gateway:
      routes:
      - id: diseases-service
        uri: http://localhost:8901/
        predicates:
        - Path=/diseases/**
      - id: doctors-service
        uri: http://localhost:8902/
        predicates:
        - Path=/doctors/**
      - id: patients-service
        uri: http://localhost:8903/
        predicates:
        - Path=/patients/**