server:
  port: 8082
  servlet:
    context-path: /springDataDemo
  
  ssl:
    enabled: true
    key-store: E:/Spring-Boot-Microservices/cert/ssl_server.jks
    key-store-password: priso_root
     
app:
  server:
    name: jpa server
    detail: this is data server
    
spring:
  profiles:
    active:
      - test
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
  application:
    name: This is the demo project for spring data jpa
    
  
