app:
  server:
    name: jboss
    detail: this is jboss for test
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    show-sql: true